# Change these first
owner: ryusei-idc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ryusei-idc.com
    url: https://ryusei-idc.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime

workflowSchedule:
  graphs:         "0 * * * *"
  responseTime:   "0 * * * *"
  staticSite:     "0 * * * *"
  summary:        "0 * * * *"
  updateTemplate: "0 * * * *"
  updates:        "0 * * * *"
  uptime:         "*/5 * * * *"

  i18n:
    footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
